---
title: "verify_data"
author: "xiaopeng.ma"
date: "2020/7/24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("~/working/Biomarker_integrated_reporter/src/my_functions.R")
load(here::here("inst/extdata/my_IMvigor210_data.RData"))
```

# single marker
## TMB
```{r, bor_TMB}
ggboxplot(data = clin.bmk, x  = "Best Confirmed Overall Response", y = "TMB",fill = "Best Confirmed Overall Response")
table(clin.bmk$`Best Confirmed Overall Response`, clin.bmk$TMB>0)
```

```{r, surv_TMB, fig.width=5, fig.height=6}
res.km <- fun.surv.km(clin.info = clin.bmk, 
                      col.time = "os", col.event = "censOS",
                      cutpoint.methods = "quartile", 
                      col.features = "TMB")
res.km$TMB$quartile$kmplot

```

## CD8T
```{r, bor_CD8T}
ggboxplot(data = clin.bmk, x  = "Best.Confirmed.Overall.Response", 
          y = "gepscore_CD.8.T.effector", fill = "Best.Confirmed.Overall.Response")
table(clin.bmk$Best.Confirmed.Overall.Response, !is.na(clin.bmk$gepscore_CD.8.T.effector))
```

```{r, surv_CD8T, fig.width=5, fig.height=6}
res.km <- fun.surv.km(clin.info = clin.bmk, 
                      col.time = "os", col.event = "censOS",
                      cutpoint.methods = "quartile", 
                      col.features = "gepscore_CD.8.T.effector")
res.km$gepscore_CD.8.T.effector$quartile$kmplot

```

## TGFB1
```{r, bor_TGFB1}
ggboxplot(data = clin.bmk, x  = "Best.Confirmed.Overall.Response", 
          y = "gep_TGFB1", fill = "Best.Confirmed.Overall.Response")
table(clin.bmk$Best.Confirmed.Overall.Response, !is.na(clin.bmk$gep_TGFB1))
```

```{r, surv_CD8T, fig.width=5, fig.height=6}
res.km <- fun.surv.km(clin.info = clin.bmk, 
                      col.time = "os", col.event = "censOS",
                      cutpoint.methods = "quartile", 
                      col.features = "gep_TGFB1")
res.km$gep_TGFB1$quartile$kmplot

```

## CXCL13
```{r, bor_CXCL13}
ggboxplot(data = clin.bmk, x  = "binaryResponse", 
          y = "gep_CXCL13", fill = "binaryResponse")
table(clin.bmk$binaryResponse, !is.na(clin.bmk$gep_CXCL13))
```

```{r, surv_CXCL13, fig.width=5, fig.height=6}
res.km <- fun.surv.km(clin.info = clin.bmk, 
                      col.time = "os", col.event = "censOS",
                      cutpoint.methods = "tertile", 
                      col.features = "gep_CXCL13")
res.km$gep_CXCL13$tertile$kmplot

```

## ARID1A
```{r, fig.width=5, fig.height=5}
res <- fun.surv.km(clin.info = clin.bmk, col.time = "os", col.event = "censOS", col.features  = "mut_ARID1A")
res$mut_ARID1A$cat$kmplot

table(clin.bmk$binaryResponse, clin.bmk$mut_ARID1A) %>% 
  prop.table(margin = 1) %>%
  fun.plot.barplot.byFixedOrder()

```


# dual marker
## TMB + CD8T
```{r}
res.quad <- fun.quadrant.analysis(data = clin.bmk, 
                      class = "binaryResponse", class.pos = "CR/PR", class.neg = "SD/PD", 
                      x1 = "TMB", x1.datatype = "cont", 
                      x2 = "gepscore_CD.8.T.effector", x2.datatype = "cont")
res.quad$stats
res.quad$test
print(res.quad$plot)
```

## TMB + TGFB1
```{r}
res.quad <- fun.quadrant.analysis(data = clin.bmk, 
                      class = "binaryResponse", class.pos = "CR/PR", class.neg = "SD/PD", 
                      x1 = "TMB", x1.datatype = "cont", 
                      x2 = "gep_TGFB1", x2.datatype = "cont", scale.pos.ratio = c(0,0.5))
res.quad$stats
res.quad$test
print(res.quad$plot)
```

## ARID1A + CXCL13
```{r}
res.quad <- fun.quadrant.analysis(data = clin.bmk, 
                      class = "binaryResponse", class.pos = "CR/PR", class.neg = "SD/PD", 
                      x1 = "mut_ARID1A", x1.datatype = "cat", x1.cat.pos = "YES", x1.cat.neg = "NO", 
                      x2 = "gep_CXCL13", x2.datatype = "cont", scale.pos.ratio = c(0,0.5))
res.quad$stats
res.quad$test
print(res.quad$plot)

```

```{r, fig.width=6, fig.height=6}
d <- clin.bmk %>% 
  mutate( gep_CXCL13_level = cut_number(gep_CXCL13,2, label=c("low","high")),
          ARID1A_CXCL13 = paste0(mut_ARID1A,gep_CXCL13_level))
res <- d %>% 
  filter(!str_detect(ARID1A_CXCL13, "NA")) %>% 
  fun.surv.km(clin.info = ., col.time = "os", 
                   col.event = "censOS", 
                   col.features = "ARID1A_CXCL13")
res$ARID1A_CXCL13$cat$kmplot

res.quad <- fun.quadrant.analysis(data = d, 
                      class = "binaryResponse", class.pos = "CR/PR", class.neg = "SD/PD", 
                      x1 = "mut_ARID1A", x1.datatype = "cat", x1.cat.pos = "YES", x1.cat.neg = "NO", 
                      x2 = "gep_CXCL13_level", x2.datatype = "cat", x2.cat.pos = "high",
                      x2.cat.neg = "low",
                      scale.pos.ratio = c(0,0.5))

print(res.quad$plot)
```

# ARID1A + TMB
```{r}
res.quad <- fun.quadrant.analysis(data = clin.bmk, 
                      class = "binaryResponse", class.pos = "CR/PR", class.neg = "SD/PD", 
                      x1 = "mut_ARID1A", x1.datatype = "cat", x1.cat.pos = "YES", x1.cat.neg = "NO", 
                      x2 = "TMB", x2.datatype = "cont", scale.pos.ratio = c(0,0.5))
res.quad$stats
res.quad$test
print(res.quad$plot)

```


# dual marker finder 
## TMB + gepscore
```{r}
targets <- clin.bmk %>% 
  colnames() %>% str_subset("gepscore_")
names(targets) <- targets
res <- map_dfr(targets, .f=  ~{
  out <- fun.quadrant.analysis(data = d, 
                      class = "binaryResponse", class.pos = "CR/PR", class.neg = "SD/PD", 
                      x1 = "TMB", x1.datatype = "cont", 
                      x2 = .x, x2.datatype = "cont", stats.only = T)
  out$stats
}, .id = "x2")

```

```{r}
m <-res %>% 
  dplyr::filter(region %in% c("R1","R2","R3","R4")) %>%
  dplyr::select(x2, region, pct.pos) %>%
  spread(key = "region", value ="pct.pos") %>%
  as.data.frame() %>%
  column_to_rownames("x2")
fun.pheatmap(m)
```

```{r, fig.width=10}
for(a.region in c("R1","R2","R3","R4")){
  x1.region <- ifelse(a.region %in% c("R1","R4"), "R14", "R23")
  tmp <- res %>% dplyr::filter(region %in% x1.region) %>% head(1)
  bor.estimate <- binom.test(tmp$n.pos, tmp$n.total)
  g <- res %>% 
    dplyr::filter(region %in% a.region) %>%
    ggbarplot(data = ., x = "x2", y = "pct.pos", sort.val = "des")+
    geom_hline(yintercept = c(bor.estimate$estimate, bor.estimate$conf.int), linetype="dashed", color ="skyblue")+
    theme.axis.agle45 + 
    labs(title = a.region)
  print(g)
}
```

## TMB + gep
```{r}
targets <- clin.bmk %>% 
  colnames() %>% str_subset("gep_") %>% setdiff(., "gep_sample_id")
names(targets) <- targets
res <- map_dfr(targets, .f=  ~{
  out <- fun.quadrant.analysis(data = clin.bmk, 
                      class = "binaryResponse", class.pos = "CR/PR", class.neg = "SD/PD", 
                      x1 = "TMB", x1.datatype = "cont", 
                      x2 = .x, x2.datatype = "cont", stats.only = T)
  out$stats
}, .id = "x2")

```

## ARID1A + gep
```{r}
targets <- clin.bmk %>% 
  colnames() %>% str_subset("gep_") %>% setdiff(., "gep_sample_id")
targets <- c("TMB", targets)
names(targets) <- targets
res <- map_dfr(targets, .f=  ~{
  out <- fun.quadrant.analysis(data = clin.bmk, 
                      class = "binaryResponse", class.pos = "CR/PR", class.neg = "SD/PD", 
                      x1 = "mut_ARID1A", x1.datatype = "cat", x1.cat.pos = "YES", x1.cat.neg = "NO", 
                      x2 = .x, x2.datatype = "cont", stats.only = T)
  out$stats
}, .id = "x2")

```


## variance explained( AIC )
```{r}
d <- as.data.frame(es.gepscore)
features <- c(make.names(rownames(es.gepscore)))
varExp1 <- t(sapply(features, function(sig) {
  fit <- glm(d[, "binaryResponse"] ~ 
    d[, sig] + d[, "FMOne.mutation.burden.per.MB"],
    family="binomial")
  fit$null.deviance - fit$deviance
}))

```



