---
title: "intro_dualmarker"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{intro_dualmarker}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, include=F}
library(dualmarker)
library(stringr)
library(dplyr)
```

# dm_pair
## Example of dm_pair, response ~ TMB + ?
```{r example, fig.width=6, fig.height=5, include=F, warning=F, message=F}
## basic example code
res.pair <- dm_pair(
   data = clin_bmk_IMvigor210, 
   # response
   #response = "binaryResponse", response.pos = "CR/PR", response.neg = "SD/PD", 
   # survival
   time = "os", event = "censOS",
   marker1 = "binaryResponse", m1.cat.pos = "CR/PR", m1.cat.neg = "SD/PD", 
   #marker2 = "TMB",
   #marker2 = "gepscore_CD.8.T.effector",
   #marker2 = "gep_MS4A2"
   #marker2 = "gep_CXCL13"
   # marker2 = "gep_CD79A"
   marker2 = "mut_STAT4", m2.cat.pos ="YES", m2.cat.neg = "NO"
   )
res.pair$survival.plot
```

# GEPscore
## Example: OS ~ gepscore
```{r}
candidates <- str_subset(colnames(clin_bmk_IMvigor210),"gepscore_")
length(candidates)
res.sm.cox.gepscore <- sm_searchM_cox(
   data = clin_bmk_IMvigor210, 
   # survival
   time = "os", event = "censOS", 
    # marker
   candidates = candidates,
   # coufounding factor
   # confound.factor = c("Baseline.ECOG.Score","Met.Disease.Status")
   confound.factor = "binaryResponse"
   )
sm_searchM_topPlot(res.sm.cox.gepscore, top.n = 10)
```

## Example: OS ~ binaryResponse + gepscore
```{r}
m2.candidates <- str_subset(colnames(clin_bmk_IMvigor210),"gepscore_")
length(m2.candidates)
res.dm.cox.gepscore <- dm_searchM2_cox(
   data = clin_bmk_IMvigor210, 
   # survival
   time = "os", event = "censOS",
   # marker1
   marker1 = "binaryResponse", m1.binarize = T, m1.cat.pos = "CR/PR", m1.cat.neg = "SD/PD",
    # marker2
   m2.candidates = m2.candidates, 
   m2.binarize = F, 
   # coufounding factor
   # confound.factor = c("Baseline.ECOG.Score","Met.Disease.Status")
   #confound.factor = "Immune.phenotype"
   )
dm_searchM2_topPlot(res.dm.cox.gepscore)
```

# GEP
## Example: survival ~ gep
```{r}
candidates <- str_subset(colnames(clin_bmk_IMvigor210),"gep_")
length(candidates)
res.sm.cox.gep <- sm_searchM_cox(
   data = clin_bmk_IMvigor210, 
   # survival
   time = "os", event = "censOS", 
    # marker
   candidates = candidates,
   # coufounding factor
   # confound.factor = c("Baseline.ECOG.Score","Met.Disease.Status")
   confound.factor = "binaryResponse"
   )
sm_searchM_topPlot(res.sm.cox.gep, top.n = 10)
```

## Example: survival ~ binaryResponse + gep
Here we demonstrated searchM2 function to combine with TMB for signatures
```{r}
m2.candidates <- str_subset(colnames(clin_bmk_IMvigor210),"gep_")
length(m2.candidates)
res.dm.cox.gep <- dm_searchM2_cox(
   data = clin_bmk_IMvigor210, 
   # survival
   time = "os", event = "censOS",
    # marker1
   marker1 = "binaryResponse", m1.binarize = T, m1.cat.pos = "CR/PR", m1.cat.neg = "SD/PD",
    # marker2
   m2.candidates = m2.candidates, 
   m2.binarize = F, 
   # coufounding factor
   # confound.factor = c("Baseline.ECOG.Score","Met.Disease.Status")
   #confound.factor = "Immune.phenotype"
)
dm_searchM2_topPlot(res.dm.cox.gep)
```

# Mutation
## Example: survival ~ mutation
```{r}
candidates <- str_subset(colnames(clin_bmk_IMvigor210),"mut_")
length(candidates)
res.sm.cox.mut <- sm_searchM_cox(
   data = clin_bmk_IMvigor210, 
   # survival
   time = "os", event = "censOS", 
    # marker
   candidates = candidates, binarize = T, cat.pos = "YES", cat.neg = "NO",
   # coufounding factor
   # confound.factor = c("Baseline.ECOG.Score","Met.Disease.Status")
   confound.factor = "binaryResponse"
   )
sm_searchM_topPlot(res.sm.cox.mut, top.n = 15)
```


## Example: survival ~ binaryResponse + mutation
```{r}
m2.candidates <- str_subset(colnames(clin_bmk_IMvigor210),"mut_")
length(m2.candidates)
res.dm.cox <- dm_searchM2_cox(
   data = clin_bmk_IMvigor210, 
    # response info
   time = "os", event ="censOS", 
   # marker1
   marker1 = "binaryResponse", m1.binarize = T, m1.cat.pos = "CR/PR", m1.cat.neg = "SD/PD",
    # marker2
   m2.candidates = m2.candidates, m2.binarize = T, m2.cat.pos = "YES", m2.cat.neg = "NO")
dm_searchM2_topPlot(res.dm.cox, 20)
```
