---
title: "searchM2"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{searchM2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(dualmarker)
library(dplyr)
library(magrittr)
library(readr)
library(tibble)
library(stringr)
```


```{r, echo=F, message=F}
es.gep <- readRDS("/usrfiles/bioinformatics/BIP_plus_resource/public_dataset/Riaz_Nivo_cell_2017_expr_norm.rds")
data <- as.data.frame(es.gep)
colnames(data) %<>% make.names()
```


```{r}
candidates <- colnames(clin_bmk_IMvigor210) %>% str_subset("gep") %>% str_replace("gep_","") %>% make.names()
candidates <- intersect(rownames(es.gep), candidates)


res <- dm_searchM2_logit(data = data, response = "response3",
                         response.pos = "1_R", response.neg = "2_NR",
                  marker1 = "state", m1.binarize = T,
                  m1.cat.pos = "On", m1.cat.neg = "Pre",
                  m2.candidates = candidates, m2.binarize = F)
dm_searchM2_topPlot(res)
```

```{r}
res.pair <- dm_pair(
  data = data, response = "response3",
  response.pos = "1_R", response.neg = "2_NR",
  marker1 = "state", m1.cat.pos = "On", m1.cat.neg = "Pre",
  marker2 = "IL2RA")

res.pair$response.plot
res.pair$survival.plot
```

