---
title: "searchM2_HCC208"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{searchM2_HCC208}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(dualmarker)
source("~/working/Biomarker_integrated_reporter/src/my_functions.R")
```

```{r load_data}
file.gep.208 <- system.file("extdata","A317_208_GEP_gep_n138x1392_2.gct", package = "dualmarker")
es.gep <- fun.read.gct(file.gep.208) %>% fun.make.eSet.from.gct()
# gepscore
file.gepscore.208 <- system.file("extdata","A317_208_GEP_gepscore_n138x443.gct", package = "dualmarker")
es.gepscore <- fun.read.gct(file.gepscore.208) %>% fun.make.eSet.from.gct()
# gepall
d1 <- as.data.frame(es.gep) %>% rownames_to_column(".id")
d2 <- t(exprs(es.gepscore)) %>% as.data.frame %>% rownames_to_column(".id")
gep.all <- left_join(d1, d2, by = ".id")

```

```{r, fig.width=6, fig.height=6}
res <- dm_pair(data = gep.all, 
        response = "BOR3", response.pos = "1_R", response.neg = "2_NR", 
        time = "PFS_month", event= "PFS_event",
        marker1 = "BOR3", m1.cat.pos = "1_R", m1.cat.neg = "2_NR",
        #marker2 = "PIPIO_EMT_WNT"
        #marker2 = "NS_IFNG_biology"
        #marker2 = "NLRC5"
        marker2 = "PVR"
        )
res$survival.plot
```

## PFS ~ CTL + gepscore 
```{r}
d <- as.data.frame(es.gepscore)
marker1 <- "CTL"
m2.candidates <- setdiff(rownames(es.gepscore), marker1)
res.cox <- dm_searchM2_cox(
  data = d, 
  time = "PFS_month", event="PFS_event", 
  marker1 = marker1, m1.binarize = F,
  m2.candidates = m2.candidates, m2.binarize = F
  )
dm_searchM2_topPlot(res.cox)

```

## response ~ CTL + gepscore 
```{r}
marker1 <- "CTL"
m2.candidates <- setdiff(rownames(es.gepscore), marker1)
res <- dm_searchM2_logit(data = gep.all, response = "BOR3", response.pos = "1_R", response.neg =  "2_NR",
                marker1 = marker1, m2.candidates = m2.candidates, m1.binarize = F, m2.binarize = F)
dm_searchM2_topPlot(res)
```


## PFS ~ response + gepscore 
```{r}
d <- as.data.frame(es.gepscore)
m2.candidates <- rownames(es.gepscore)
res.cox <- dm_searchM2_cox(
  data = d, 
  time = "PFS_month", event="PFS_event", 
  marker1 = "BOR3", m1.binarize = T, m1.cat.pos = "1_R", m1.cat.neg = "2_NR",
  m2.candidates = m2.candidates, m2.binarize = F
  )
dm_searchM2_topPlot(res.cox)
```


## PFS ~ response + gep
```{r}
d <- as.data.frame(es.gep)
m2.candidates <- rownames(es.gep)
res.cox <- dm_searchM2_cox(
  data = d, 
  time = "PFS_month", event="PFS_event", 
  marker1 = "BOR3", m1.binarize = T, m1.cat.pos = "1_R", m1.cat.neg = "2_NR",
  m2.candidates = m2.candidates, m2.binarize = F
  )
dm_searchM2_topPlot(res.cox)
```
